// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies_Exercice3.Data;

#nullable disable

namespace Movies_Exercice3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250410125547_ModelCreation")]
    partial class ModelCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exercice3 - Movies.Models.MovieTheater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieTheater");
                });

            modelBuilder.Entity("Exercice3 - Movies.Models.ScheduledScreening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationsCount")
                        .HasColumnType("int");

                    b.Property<int?>("ScreenRoomId")
                        .HasColumnType("int");

                    b.Property<int>("ScreeningRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ScreenRoomId");

                    b.ToTable("ScheduledScreening");
                });

            modelBuilder.Entity("Exercice3 - Movies.Models.ScreenRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("MovieTheaterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieTheaterId");

                    b.ToTable("ScreenRoom");
                });

            modelBuilder.Entity("Exercice3 - Movies.Models.ScheduledScreening", b =>
                {
                    b.HasOne("Exercice3 - Movies.Models.ScreenRoom", null)
                        .WithMany("ScheduledScreenings")
                        .HasForeignKey("ScreenRoomId");
                });

            modelBuilder.Entity("Exercice3 - Movies.Models.ScreenRoom", b =>
                {
                    b.HasOne("Exercice3 - Movies.Models.MovieTheater", null)
                        .WithMany("ScreenRooms")
                        .HasForeignKey("MovieTheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exercice3 - Movies.Models.MovieTheater", b =>
                {
                    b.Navigation("ScreenRooms");
                });

            modelBuilder.Entity("Exercice3 - Movies.Models.ScreenRoom", b =>
                {
                    b.Navigation("ScheduledScreenings");
                });
#pragma warning restore 612, 618
        }
    }
}
