// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies_Exercice3.Data;

#nullable disable

namespace Movies_Exercice3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250410122959_testRelation")]
    partial class testRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exercice3 - Movies.Models.MovieTheater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("MovieTheater");
                });

            modelBuilder.Entity("Exercice3 - Movies.Models.ScreenRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MovieTheaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieTheaterId");

                    b.ToTable("ScreenRoom");
                });

            modelBuilder.Entity("Exercice3 - Movies.Models.ScreenRoom", b =>
                {
                    b.HasOne("Exercice3 - Movies.Models.MovieTheater", null)
                        .WithMany("ScreenRooms")
                        .HasForeignKey("MovieTheaterId");
                });

            modelBuilder.Entity("Exercice3 - Movies.Models.MovieTheater", b =>
                {
                    b.Navigation("ScreenRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
