services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU18-ubuntu-22.04
    container_name: sqlserver-movies
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
  
  app:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: app-movies
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - sqlserver
    tty: true
      
volumes:
  sqlserver_data: